openapi: 3.0.1
info:
  title: Order Service
  description: Order CRUD API.
  version: 1.0.0
servers:
  - url: /v2
paths:
  /customer:
    get:
      summary: Get customers
      operationId: getCustomers
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    post:
      summary: Create a customer
      operationId: createCustomer
      requestBody:
        $ref: '#/components/requestBodies/SaveCustomerRequest'
      responses:
        200:
          description: Successful response
    put:
      summary: Update customer by id
      operationId: updateCustomer
      requestBody:
        $ref: '#/components/requestBodies/SaveCustomerRequest'
      responses:
        200:
          description: Successful response
  /customer/{id}:
    get:
      summary: Get customer by id
      operationId: getCustomer
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
    delete:
      summary: Delete customer by id
      operationId: deleteCustomer
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Successful response
  /authenticate:
    post:
      summary: Authenticate API users
      operationId: authenticate
      requestBody:
        description: Authentication request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JwtRequest'
      responses:
        200:
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtResponse'
components:
  parameters:
    id:
      in: path
      name: id
      schema:
        type: number
      required: true
      description: Numeric ID of the item to get
  requestBodies:
    SaveCustomerRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Customer'
    JwtRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/JwtRequest'
  responses:
    JwtResponse:
      $ref: '#/components/schemas/JwtResponse'
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Sanderson
        email:
          type: string
          example: jsanderson@gmail.com
    Contact:
      type: object
      properties:
        id:
          type: integer
          format: int64
        customerId:
          type: integer
          format: int64
        phoneNumber:
          type: string
          example: +35699720374
        address:
          type: string
          example: 443 Trig D'Argens
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        productType:
          type: string
          enum: [ "Internet", "TV", "Telephony", "Mobile" ]
        package:
          type: string
          example: 250Mbit
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        productId:
          type: integer
          format: int64
        contactId:
          type: integer
          format: int64
    CreateCustomerRequest:
      $ref: '#/components/schemas/Customer'
    JwtRequest:
      type: object
      properties:
        username:
          type: string
          example: j.sanderson
        password:
          type: string
          example: g6dpq38kY7ENmdnqBrRHssy
    JwtResponse:
      type: object
      properties:
        jwtToken:
          type: string
          example: 5ktH96mqT3ZERwyyhWZtQ5V